server :
  port : 80

spring :
    thymeleaf :
       prefix : thyme/
       suffix : .html
       cache : false
         
    datasource :
        driver-class-name : org.mariadb.jdbc.Driver
        # allowMultiQueries=true 다중쿼리 실행 가능
        url : jdbc:mariadb://localhost:3306/green_db?allowMultiQueries=true
        username : green
        password : 1234

mybatis :
    type-aliases-package : aaa.db